name: Playwright Tests Workflow

on:
  push:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      pgconn: ${{ secrets.PGCONN }}

    steps:

      # Step 0: Setup Node.js for Angular
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'

      # Step 1: Install Angular CLI
      - name: Install Angular CLI
        run: npm install -g @angular/cli
        
      # Step 2: Setup .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      # Step 3: Checkout the current repository
      - name: Checkout code
        uses: actions/checkout@v4
          
      # Step 4: Install Angular dependencies
      - name: Install Angular dependencies
        run: |
            cd frontend
            npm install
            ng build
          
      # Step 5: Install Playwright Test dependencies 
      - name: Install Playwright Test dependencies
        run: npm install
        working-directory: ./Infrastructure.Tests/PlaywrightTests 
          
      # Step 6: Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install
        working-directory: ./Infrastructure.Tests/PlaywrightTests

      # Step 7: Sleep to allow time for the API to start
      - name: Sleep for 60 seconds
        run: sleep 60s
      
      # Step 8: Run Playwright Tests
      - name: Run Playwright Tests
        run: |
          cd Infrastructure.Tests
          dotnet test Infrastructure.Tests.csproj
